import type { Metadata } from "next";
import "./globals.css";
import Header from "@/layout/header";
import Sidebar from "@/layout/sidebar";
import Footer from "@/layout/footer";

export const metadata: Metadata = {
  title: "Mentoris",
  description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <div className="flex flex-row w-full">
               <Sidebar />
               <div className="flex flex-col w-full ml-28 xl:ml-52">
                  <Header />        
                  <div className="flex flex-row w-full bg-secondary">
                     <div>
                     {children}
                     </div>
                  </div>
               </div>   
            </div>
            <Footer />
         </body>
      </html>
   );
}
