import type { Metadata } from "next";
import "./globals.css";
import Header from "@/layout/header";
import Sidebar from "@/layout/sidebar";
import Footer from "@/layout/footer";

export const metadata: Metadata = {
  title: "Mentoris",
  description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <Header />        
            <div className="flex flex-row">
               <Sidebar />
               <div className="flex flex-row w-full z-0 bg-secondary">
                  <div>
                  {children}
                  </div>
               </div>
            </div>   
            <Footer />
         </body>
      </html>
   );
}
